############################# English ############################
[en]
languageName = "En"
title = "Bigspring Hugo"
contentDir = "content/english" # content/english
weight = 1
########### footer content ##########
footer_menu_left = "Company"
footer_menu_middle = "Product"
footer_menu_right = "Support"
footer_content = "We don't believe the idea of a Republic is only a political one. It's an idea that showcases the benefits of relying on each other's strengths to improve together, while maintaining appropriate independence. We believe that a rising tide can lift all ships. Find out how our expertise can help lift your revenue, sales, and traffic, while improving overall business capabilities."
# copyright
copyright = ""



############################# Deutsch ############################
[de]
languageName = "De"
title = "Bigspring Hugo"
contentDir = "content/deutsch" # content/german
weight = 2
########### footer content ##########
footer_menu_left = "Firma"
footer_menu_middle = "Produkte"
footer_menu_right = "Support"
footer_content = "Lorem ipsum dolor sit amet, consectetur elit. Consjat tristique eget amet, tempus eu at cttur."
# copyright
copyright = ""