# main menu
[[main]]
name = ""
url = ""
weight = 1

[[main]]
name = "Our Services"
url = "blog/"
weight = 2

[[main]]
name = "Pricing"
url = "pricing/"
weight = 3

[[main]]
name = "Contact"
url = "contact/"
weight = 4



# footer menu left
[[footer_left]]
name = "About Us"
url = "#"



[[footer_left]]
name = "Pricing"
url = "pricing/"


# footer menu middle
[[footer_middle]]
name = "Pricing"
url = "pricing/"

[[footer_middle]]
name = "Platform"
url = "#"


# footer menu right
[[footer_right]]
name = "Privacy Policy"
url = "privacy-policy/"


